# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Kwiki-UserName-Cookie
version:      0.01
version_from: lib/Kwiki/UserName/Cookie.pm
installdirs:  site
requires:
    Kwiki::Installer:              0
    Kwiki::UserName:               0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.20
